title: 
email: rullbeng@gmail.com
description: >- 
baseurl: "" 
url: "https://www.ruben-gz.com"
twitter_username: rullbem
github_username:  rullbem

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass: 
  sass_dir: _sass
  style: compressed